version: "3.9"

services:
  backend:
    build: ./backend   # Path to your FastAPI or Django backend
    container_name: support_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: support_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: support_user
      POSTGRES_PASSWORD: support_pass
      POSTGRES_DB: support_db
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: support_pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@support.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - db

volumes:
  db_data:
